"use client";
import React, { useEffect, useState } from 'react';
import ColdEmailsTable from '@/components/ColdEmailsTable';

export default function ColdEmailsPage() {
  const [coldEmails, setColdEmails] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdated, setLastUpdated] = useState<string>('');

  useEffect(() => {
    setLoading(true);
    async function fetchColdEmails() {
      try {
        const res = await fetch('/api/cold-emails');
        const data = await res.json();
        if (res.ok) setColdEmails(data.cold_emails);
        else setError(data.error || 'Failed to fetch cold emails');
      } catch (err: any) {
        setError(err.message);
      }
      setLoading(false);
      setLastUpdated(new Date().toLocaleTimeString());
    }
    fetchColdEmails();
  }, []);

  const todayCount = coldEmails.filter(e => {
    if (!e.scheduled_time) return false;
    const emailDate = new Date(e.scheduled_time).toDateString();
    const today = new Date().toDateString();
    return emailDate === today;
  }).length;

  const sentCount = coldEmails.filter(e => e.status === 'Sent').length;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-xl shadow-lg p-8 mb-8">
        <div className="flex items-center gap-4 mb-4">
          <span className="bg-indigo-100 text-indigo-700 rounded-full p-2">
            <svg width="28" height="28" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 12H8m8 0a4 4 0 11-8 0 4 4 0 018 0zm0 0v4m0-4V8" /></svg>
          </span>
          <h1 className="text-2xl font-bold text-indigo-700 tracking-tight">Cold Emails</h1>
        </div>
        <p className="text-gray-600 mb-4">View and manage all AI-generated cold emails scheduled for outreach. Stay on top of your pipeline and ensure every lead gets timely attention.</p>
        <div className="flex flex-wrap gap-4 mb-6">
          <div className="bg-indigo-50 rounded-lg px-4 py-2 text-indigo-700 font-semibold text-sm shadow">Today: {todayCount}</div>
          <div className="bg-blue-50 rounded-lg px-4 py-2 text-blue-700 font-semibold text-sm shadow">Total Scheduled: {coldEmails.length}</div>
          <div className="bg-green-50 rounded-lg px-4 py-2 text-green-700 font-semibold text-sm shadow">Sent: {sentCount}</div>
        </div>
        <div className="flex items-center gap-2 mb-4">
          <button className="bg-gradient-to-r from-indigo-500 to-blue-500 text-white px-4 py-2 rounded-lg font-semibold shadow hover:from-indigo-600 hover:to-blue-600 transition">Refresh</button>
          {lastUpdated && <span className="text-xs text-gray-400">Last updated: {lastUpdated}</span>}
        </div>
        {loading ? (
          <div className="py-8 text-center text-gray-400">Loading...</div>
        ) : error ? (
          <div className="py-8 text-center text-red-500">{error}</div>
        ) : (
          <ColdEmailsTable coldEmails={coldEmails} />
        )}
        <div className="mt-8 text-xs text-gray-500">
          <p>💡 <b>Tip:</b> Click on a row to view the full email preview and take action. Cold emails are generated by your AI agent and scheduled based on your outreach strategy.</p>
        </div>
      </div>
    </div>
  );
} 